### ISSUE TITLE
no wasm in ppci official ?

### ISSUE THREAD

**Issue by stonebig** [almarklein/rocket_rust_py#2]
trying the notebook I get this error:
````
Slide Type

from rocket_qt import QtRocketGame
game = QtRocketGame()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-381cdde5c8d1> in <module>()
----> 1 from rocket_qt import QtRocketGame
      2 game = QtRocketGame()

C:\WinP\bd37\bu\winp64-3.7.x.2\notebooks\rocket_rust_py-master\rocket_qt.py in <module>()
      7 from qtpy import QtWidgets, QtCore, QtGui
      8 
----> 9 from rocket import BaseRocketGame
     10 
     11 REL_SIZE = 2.5

C:\WinP\bd37\bu\winp64-3.7.x.2\notebooks\rocket_rust_py-master\rocket.py in <module>()
     15 import os
     16 
---> 17 from ppci import wasm
     18 from ppci.utils.reporting import HtmlReportGenerator
     19 

ImportError: cannot import name 'wasm' from 'ppci' (C:\WinP\bd37\bu\winp64-3.7.x.2\python-3.7.0.amd64\lib\site-packages\ppci\__init__.py)

````

**Comment by stonebig** [comment]
ok:
- last official release ppci-0.5.5.tar.gz is from 2018-01-07
- a lot of things have changed around WASM since 2018-05-01

**Comment by stonebig** [comment]
Hi again @almarklein,

I will embed a compacted form of this directory in next winpython, with ppci and a link to youtube europython 2018.

Let me know if it's a problem (I kept all the licences and references)

https://github.com/winpython/winpython_afterdoc/tree/master/docs/WASM_almar_klein_demo

**Comment by almarklein** [comment]
Cool, thanks for spreading the word of WASM this way :)

**Comment by GoodManWEN** [comment]
Encountering the same problem(can not import ppci.wasm) in 2021.8.9, and the version of ppci is `0.5.5`.

**Comment by almarklein** [comment]
ppci 0.5.5 is from 2018 - you'd need to update it (`pip install -U ppci`)
